[build]
target = "index.html"
dist = "dist"
public_url = "/"
filehash = true

[serve]
addresses = ["127.0.0.1"]
port = 8080

[[proxy]]
backend = "http://127.0.0.1:7777/api/"

[[proxy]]
backend = "ws://127.0.0.1:7777/"
rewrite = "/ws/"
ws = true

[[proxy]]
backend = "http://127.0.0.1:7777/vendor/"

[[proxy]]
backend = "http://127.0.0.1:7777/img/"
